spring:
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

#otel:
#  exporter:
#    otlp:
#      endpoint: http://localhost:4317
#  traces:
#    exporter: otlp
#  metrics:
#    exporter: none
#  logs:
#    exporter: none

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      access: unrestricted
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true