replicaCount: 1

image:
  repository: todo-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://opentelemetry-collector:4317
  - name: OTEL_SERVICE_NAME
    value: "todo-app"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

grafana:
  fullnameOverride: "grafana"
  service:
    type: NodePort
    nodePort: 30030
  adminUser: admin
  adminPassword: admin

tempo:
  fullnameOverride: "tempo"
  enabled: true
  mode: deployment
  tempo:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14317
          http:
            endpoint: 0.0.0.0:14318
  service:
    ports:
      - name: grpc
        port: 14317
        targetPort: grpc
      - name: http
        port: 14318
        targetPort: http
  persistence:
    enabled: false

opentelemetry-collector:
  fullnameOverride: "opentelemetry-collector"
  enabled: true
  mode: deployment
  config:
    exporters:
      debug:
        verbosity: detailed
      otlp/grafana-tempo:
        endpoint: tempo:14317
        tls:
          insecure: true
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          exporters: [debug]
        traces:
          receivers: [otlp]
          exporters: [debug, otlp/grafana-tempo]