replicaCount: 1

image:
  repository: todo-app
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

env:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: http://todo-app-otel-collector:4318
  - name: OTEL_SERVICE_NAME
    value: "todo-app"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

prometheus:
  server:
    service:
      type: NodePort
      nodePort: 30090
  prometheusSpec:
    scrapeInterval: 15s
    additionalScrapeConfigs:
      - job_name: 'todo-app'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['todo-app:8080']

grafana:
  service:
    type: NodePort
    nodePort: 30030
  adminUser: admin
  adminPassword: admin

opentelemetry-collector:
  enabled: true
  mode: deployment
  service:
    enabled: true
    type: NodePort
  config:
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          exporters: [debug]
        traces:
          receivers: [otlp]
          exporters: [debug]